'''
@file: SConscript
@date: Okt 21, 2012

@brief: Cross compilation SConscript for utils package.
@version: 2.0 

@author: Milos Subotic milos.subotic.sm@gmail.com
@license: MIT
'''

###############################################################################

from __future__ import print_function

###############################################################################

import Package
import Utils

###############################################################################

Import('sconscriptArgs')
project = sconscriptArgs.project

###############################################################################

staticLibPackage = Package.StaticLibraryPackage(
	project = project,
	packageName = Utils.getCurrentDirName(),
	publicPackage = True,
	exportedIncludeDirs = [ 'include' ]
)
if Utils.hostPlatform() == 'linux':
	staticLibPackage.libs.append('rt')

staticLibPackage.build()

###############################################################################

