#! /usr/bin/env python
# encoding: utf-8

'''
@file: wscript
@date: Aug 30, 2014

@author: Milos Subotic <milos.subotic.sm@gmail.com>
@license: MIT

@brief: Waf script for building utils package.

@version: 1.0
Changelog:
1.0 - Initial version.

'''

###############################################################################

import sys

def options(opt):
	pass

def configure(conf):
	conf.env.CXXFLAGS.append('-std=c++11')
	conf.define('__STDC_INT64__', 1)

	if sys.platform.startswith('linux'):
		conf.check(
			compiler = 'cxx',
			lib = 'rt',
			mandatory = True, 
			uselib_store = 'LIBRT'
		)

def build(bld):
	bld.stlib(
		source = bld.path.ant_glob('src/*.cpp'),
		includes = 'include',
		export_includes = 'include',
		use = 'LIBRT pthread',
		target = 'utils'
	)

###############################################################################

