#! /usr/bin/env python
# encoding: utf-8

'''
@file: wscript
@date: Sep 6, 2014

@author: Milos Subotic <milos.subotic.sm@gmail.com>
@license: MIT

@brief: Waf script for building coloring_tee package.

@version: 1.0
Changelog:
1.0 - Initial version.

'''

###############################################################################

def options(opt):
	pass

def configure(conf):
	conf.check_cfg(
		package = 'lua5.1',
		uselib_store = 'LUA',
		args = '--cflags --libs',
		mandatory = True
	)

def build(bld):
	bld.program(
		source = bld.path.ant_glob('src/*.cpp'),
		includes = [ 'src', bld.out_dir ],
		use = 'utils LUA',
		target = 'coloring_tee'
	)

###############################################################################

